### ISSUE TITLE
Intake-sql feedstock should be pinned to sqlalchemy>2

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/intake-sql-feedstock#3]
### Comment:

@martindurant 

I noticed this discrepancy while trying to resolve some poetry environment vs conda env issues. 
pip install intake-sql picks intake-sql version 0.3.0 - if have an existing package that requires sqlalchemy<2
but conda install intake-sql will install intake-sql version 0.4.0

LMK if you would like me to raise a PR to fix the feedstock - and make it consistent with source /pip installs.

References 
https://github.com/intake/intake-sql/blob/0.4.0/requirements.txt
https://github.com/conda-forge/intake-sql-feedstock/blob/main/recipe/meta.yaml#L28

**Comment by martindurant** [comment]
I suppose both those installs end up with a working package? If so, I would suggest not changing anything. pip's resolver will always be less comprehensive than conda/mamba. I suppose you can always run with `-U` and hope things turn out OK.

Note that in [intake 2](https://github.com/intake/intake/pull/737) the SQL catalog and soruce(s) are moved into the intake main package.

**Comment by rxm7706** [comment]
Thanks @martindurant - Appreciate the note. 

> I suppose both those installs end up with a working package? If so, I would suggest not changing anything. 

Yes, that's correct. 

> Note that in [intake 2](https://github.com/intake/intake/pull/737) the SQL catalog and soruce(s) are moved into the intake main package.

That is great to know ! looking forward to the rewrite/V2 ! Looks like a massive effort !
